version: "3.3"
   
services:

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 443:443
    volumes:
      - ./nginx_conf:/etc/nginx/conf.d
      - ./app/static:/var/www/static
      - ./certificates/:/certificates
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - smartship_front
  smartship_front:
    build: .
    volumes:
      - ./app:/app