version: "3.3"

services:

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 443:443
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./app/static:/var/www/static
      - /etc/ssl/certbot_smartshipping/conf:/etc/letsencrypt
      - /etc/ssl/certbot_smartshipping/www:/var/www/certbot
    depends_on:
      - smartship_front
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done &
      nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/ssl/certbot_smartshipping/conf:/etc/letsencrypt
      - /etc/ssl/certbot_smartshipping/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h &
      wait $${!}; done;'"

  smartship_front:
    build: .
    volumes:
      - ./app:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /var/lib/mongo/smartshipping/:/data/db
