version: "3.3"

services:

#  nginx:
#    image: nginx:1.21.3-alpine
#    ports:
#      - 5080:80
#    volumes:
#      - ./data/nginx:/etc/nginx/conf.d
#      - ./app/static:/var/www/static
#      - /etc/ssl/certbot_smartshipping/conf:/etc/letsencrypt
#      - /etc/ssl/certbot_smartshipping/www:/var/www/certbot
#    depends_on:
#      - smartship_front
#    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done &
#      nginx -g \"daemon off;\"'"
#
#  certbot:
#    image: certbot/certbot
#    volumes:
#      - /etc/ssl/certbot_smartshipping/conf:/etc/letsencrypt
#      - /etc/ssl/certbot_smartshipping/www:/var/www/certbot
#    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h &
#      wait $${!}; done;'"
#
  smartship_front:
    build: .
    ports:
      - 5090:5000
    volumes:
      - ./app:/app
